info:
  component: Edge Server

endpoints:
  restart:
    enabled: true

auth:
  ribbon:
    listOfServers: http://localhost:5000
    ServerListRefreshInterval: 15000

companyService:
  ribbon:
    listOfServers: http://localhost:9050

plutosTaxService:
  ribbon:
    listOfServers: http://localhost:3000

countryService:
  ribbon:
    listOfServers: http://localhost:4040

currencyService:
  ribbon:
    listOfServers: http://localhost:9090

guardianAuthorizationService:
  ribbon:
    listOfServers: http://localhost:9800

dionysusEventMicroservice:
  ribbon:
    listOfServers: http://localhost:9400

hermesShippingRuleService:
  ribbon:
    listOfServers: http://localhost:10000


zuul:
  ignoredServices: '*'
  requestUriKey: /api
  health:
    enabled: true
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: auth
      stripPrefix: false
    country_service:
      path: /resources/geo/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: countryService
      stripPrefix: true
    companyService:
      path: /api/company/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: companyService
      stripPrefix: true
    plutosTaxService:
      path: /api/accounting/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: plutosTaxService
      stripPrefix: true
    currencyService:
      path: /resources/money/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: currencyService
      stripPrefix: true
    guardianAuthorizationService:
      path: /resources/authorization/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: guardianAuthorizationService
      stripPrefix: true
    dionysusEventMicroservice:
      path: /api/events/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: dionysusEventMicroservice
      stripPrefix: true
    hermesShippingRuleService:
      path: /api/shipping/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: hermesShippingRuleService
      stripPrefix: true

eureka:
  client:
    enabled: false

ribbon:
  UseIPAddrForServer: true
  eureka:
    enabled: false

server:
  port: 8080

debug: true
trace: false
logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace